<div class="panel-body">
	<label class="small">All Pages:</label>
	<div class="row">
		<div class="col-xs-12">
			<position>menu</position>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12">
			<position>breadcrumb</position>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12">
			<main/>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12">
			<position>bottom</position>
		</div>
	</div>
</div>

<div class="panel-body">
	<label class="small">Home Control Panel:</label>
	<div class="row">
		<div class="col-xs-12">
			<position>menu</position>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-4">
			<position>left</position>
		</div>
		<div class="col-xs-4">
			<position>center</position>
		</div>
		<div class="col-xs-4">
			<position>right</position>
		</div>
	</div>
	<div class="row">
		<div class="col-xs-12">
			<position>bottom</position>
		</div>
	</div>
</div>