<form action="" id="adminForm" name="adminForm" method="post" enctype="multipart/form-data">	
	<div class="row">
		<nav class="navbar navbar-default" role="navigation">
			<div class="container-fluid">
			<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						<span class="sr-only">Toggle navigation</span>
						&nbsp;<span class="glyphicon glyphicon-cog"></span>&nbsp;
					</button>
					<a class="navbar-brand" href="#">Category Manager : New Category</a>
				</div>
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav navbar-right">
						<input id="task" name="task" type="hidden" value="edit"/>
						<button type="submit" class="btn btn-default btn-sm btn-primary navbar-btn"><span class="glyphicon glyphicon-floppy-saved"></span> Save</button>
						<button type="submit" onclick="$('#task').val('edit.close');" class="btn btn-default btn-sm navbar-btn"><span class="glyphicon glyphicon-floppy-remove"></span> Save & Close</button>
						<button type="submit" onclick="$('#task').val('edit.new');" class="btn btn-default btn-sm navbar-btn"><span class="glyphicon glyphicon-floppy-disk"></span> Save & New</button>
						<button type="submit" onclick="$('#task').val('edit.copy');" class="btn btn-default btn-sm navbar-btn"><span class="glyphicon glyphicon-floppy-disk"></span> Save & Copy</button>
						<button type="submit" onclick="$('#task').val('close');" class="btn btn-default btn-sm btn-danger navbar-btn"><span class="glyphicon glyphicon-remove"></span> Close</button>
					</ul>
				</div>
			</div>
		</nav>
		<div class="panel panel-default">
			<div class="panel-body">
				<div class="row">
					<div class="col-md-12">
						<div class="row">
							<div class="col-md-8"><?php echo $this->form->title;?></div>
							<div class="col-md-4">
 								<?php echo $this->form->alias;?>
							</div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<ul class="nav nav-tabs">
							<li class="active"><a href="#category" data-toggle="tab">Category</a></li>
							<li class=""><a href="#options" data-toggle="tab">Infomations</a></li>
							<?php if ($this->isAllow('contents', 'config')){?>
							<li class=""><a href="#permissions" data-toggle="tab">Permissions</a></li>
							<?php } ?>
						</ul>
						<div class="tab-content" style="overflow:hidden;">
							<div class="tab-pane active" id="category">
								<div class="row" style="margin-top:15px;">
									<div class="col-md-9">
										<?php echo $this->form->description;?>
									</div>
									<div class="col-md-3">
										<?php echo $this->form->category;?>
									</div>
								</div>
							</div>
							<div class="tab-pane form-horizontal" id="options">
								<div class="row" style="margin-top:20px;">
									<div class="col-md-6">
										<?php echo $this->form->publish;?>
									</div>
									<div class="col-md-6">
										<?php echo $this->form->seo;?>
									</div>
								</div>
							</div>
							<?php if ($this->isAllow('contents', 'config')){?>
							<div class="tab-pane" id="permissions">
								<div class="row" style="margin-top:20px;">
									<div class="col-md-12">
										<?php echo $this->permission;?>
									</div>
								</div>
							</div>
							<?php }?>
						</div>
					</div>
				</div>
				
			</div>
		</div>
	</div>
	<div class="modal fade" tabindex="-1" id="orderModal" role="dialog" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title">Order Category <smal>Drag & Drop</h4>
				</div>
				<div class="modal-body">
					<div class="dd" data-id="1">
					    <?php echo $this->order_category; ?>			    
					</div>
					<div class="clearfix"></div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Ok</button>
				</div>		
			</div>
		</div>
	</div>
	<?php echo $this->form->hidden;?>
</form>