<div class="form-inline form-full-right">    
    <div class="form-group">
	    <ul class="pagination pagination-sm"  style="margin: 0px; padding: 5px 0px 0px 0px;">
	        <!-- Previous page link -->
	        <?php if(isset($this->previous)) {?>
	        	<li><a href="<?php echo $this->baseUrl($this->route(array('action' => 'index', 'page' => $this->first), null, false)); ?>" data-toggle="tooltip" title="Start"><span class="glyphicon glyphicon-fast-backward"></span></a></li>
	        	<li><a href="<?php echo $this->baseUrl($this->route(array('action' => 'index', 'page' => $this->previous), null, false)); ?>" data-toggle="tooltip" title="Previous"><span class="glyphicon glyphicon-backward"></span></a></li>
	        <?php }else{?>
	        	<li class="disabled"><a href="#"><span class="glyphicon glyphicon-fast-backward"></span></a></li>
	        	<li class="disabled"><a href="#"><span class="glyphicon glyphicon-backward"></span></a></li>
	        <?php }?>
	        
	        <!-- Numbered page link -->
	        <?php foreach($this->pagesInRange as $page){?>
	            <?php if($page != $this->current){?>
	                <li><a href="<?php echo $this->baseUrl($this->route(array('action' => 'index', 'page' => $page), null, false)); ?>" data-toggle="tooltip" title="Page <?= $page;?>"><?= $page;?></a></li>
	            <?php }else{?>
	                <li class="active"><a href="#"><?= $page;?><span class="sr-only">(current)</span></a></li>
	            <?php }?>
	        <?php }?>
	        <!-- Next page link $this->next-->
	        <?php if(isset($this->next)){?>
	            <li><a href="<?php echo $this->baseUrl($this->route(array('action' => 'index', 'page' => $this->next), null, false)); ?>" data-toggle="tooltip" title="Next"><span class="glyphicon glyphicon-forward"></span></a></li>
	            <li><a href="<?php echo $this->baseUrl($this->route(array('action' => 'index', 'page' => $this->last), null, false)); ?>" data-toggle="tooltip" title="End"><span class="glyphicon glyphicon-fast-forward"></span></a></li>
	        <?php }else{?>
	        	<li class="disabled"><a href="#"><span class="glyphicon glyphicon-forward"></span></a></li>
	        	<li class="disabled"><a href="#"><span class="glyphicon glyphicon-fast-forward"></span></a></li>
	        <?php }?>
	    </ul>
    </div>
</div>
<div class="clearfix"></div>