<form action="" id="adminForm" name="adminForm" method="post">	
	<div class="row">
		<nav class="navbar navbar-default" role="navigation">
			<div class="container-fluid">
			<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-2">
						<span class="sr-only">Toggle navigation</span>
						&nbsp;<span class="glyphicon glyphicon-cog"></span>&nbsp;
					</button>
					<a class="navbar-brand" href="#">User Manager : Users</a>
				</div>
				<div class="collapse navbar-collapse" id="navbar-collapse-2">
					<ul class="nav navbar-nav navbar-right">
						<input id="task" name="task" type="hidden" value="edit"/>
						<button type="button" onclick="$('#task').val('create');$(this).closest('form').submit();" class="btn btn-default btn-sm btn-primary navbar-btn" <?php echo ($this->isAllow('users', 'create') == true ? '' : ' disabled')?>><span class="glyphicon glyphicon-plus-sign"></span> New</button>
						<button type="button" onclick="if(!$(this).closest('form').find('table :checked').first().val()){alert('Please first make a selection from the list!');return false;}else{$('#task').val('edit');$(this).closest('form').submit();};" class="btn btn-default btn-sm navbar-btn"><span class="glyphicon glyphicon-edit"></span> Edit</button>
						<button type="button" onclick="if(!$(this).closest('form').find('table :checked').first().val()){alert('Please first make a selection from the list!');return false;}else{$('#task').val('enable');$(this).closest('form').submit();};" class="btn btn-default btn-sm navbar-btn"><span class="glyphicon glyphicon-ok text-success"></span> Enable</button>
						<button type="button" onclick="if(!$(this).closest('form').find('table :checked').first().val()){alert('Please first make a selection from the list!');return false;}else{$('#task').val('disable');$(this).closest('form').submit();};" class="btn btn-default btn-sm navbar-btn"><span class="glyphicon glyphicon-remove text-danger"></span> Disable</button>
						<button type="button" onclick="if(!$(this).closest('form').find('table :checked').first().val()){alert('Please first make a selection from the list!');return false;}else{$('#task').val('activate');$(this).closest('form').submit();};" class="btn btn-default btn-sm navbar-btn"><span class="glyphicon glyphicon-ok text-primary"></span> Activate</button>
						<button type="button" onclick="if(!$(this).closest('form').find('table :checked').first().val()){alert('Please first make a selection from the list!');return false;}else{$('#task').val('delete');$(this).closest('form').submit();};" class="btn btn-default btn-sm btn-danger navbar-btn"><span class="glyphicon glyphicon-remove-sign"></span> Delete</button>
						
					</ul>
				</div>
			</div>
		</nav>
		<ul class="nav nav-tabs">
			<li class="active"><a href="#">User</a></li>
			<li><a href="<?= $this->url(array('module' => 'users', 'controller'=>'groups', 'action'=>'index'), null, true); ?>">Group</a></li>
		</ul>
		<!-- Table -->
		<div class="panel panel-default tabs-panel">
			<div class="panel-body">
				<div class="row">
					<div class="col-sm-4 form-group">
						<div class="input-group">
							<input value="<?php echo $this->filter['search']; ?>" name="filter_search" id="filter_search" placeholder="Search Users" type="text" class="form-control input-sm">
							<span class="input-group-btn">
								<button class="btn btn-default btn-sm" type="button" onclick="$(this).closest('form').submit();">Search</button>
								<button class="btn btn-default btn-sm" type="button" onclick="$('#filter_search').val(''); $(this).closest('form').submit();">Reset</button>
							</span>
						</div>
					</div>
					<div class="col-sm-8">
						<div class="form-inline form-full-right">
							<div class="form-group input-sm hidden-xs">
								<label>Filter by: </label>
							</div>
						    <div class="form-group">
						    	<?php echo $this->formSelect('filter_state', $this->filter['state'], array('class' => 'form-control input-sm', 'onchange' => '$(this).closest(\'form\').submit();'), array(
						    			'*' => ' - State - ',
						    			1 => 'Enabled',
						    			0 => 'Disabled'
						    	));?>
						    </div>
						    <div class="form-group">
						    	<?php echo $this->formSelect('filter_status', $this->filter['status'], array('class' => 'form-control input-sm', 'onchange' => '$(this).closest(\'form\').submit();'), array(
						    			'*' => ' - Active - ',
						    			1 => 'Activated',
						    			0 => 'Unactivated'
						    	));?>
						    </div>
						    <div class="form-group">
								<?php echo $this->formSelect('filter_group', $this->filter['group'], array('class' => 'form-control input-sm', 'onchange' => '$(this).closest(\'form\').submit();'), array(
										'*' => ' - Group - ')
										+ $this->select_groups
								);?>						    
						    </div>
						</div>
					</div>
					<div class="clearfix"></div>
				</div>
				<div class="panel panel-default margin-fix table-responsive">
					<table class="table table-hover table-striped">
						<thead>
							<tr>
								<th width="1%"><input type="checkbox" onchange="$(this).closest('form').find('table :checkbox').prop('checked', this.checked);"></th>
								<th><?php echo $this->order('Real Name', 'real_name'); ?></th>
								<th class="text-center"><?php echo $this->order('Username', 'username'); ?></th>
								<th class="text-center"><?php echo $this->order('Enabled', 'block'); ?></th>
								<th class="text-center"><?php echo $this->order('Activated', 'active'); ?></th>
								<th class="text-center">User Group</th>
								<th class="text-center"><?php echo $this->order('Email', 'email'); ?></th>
								<th class="text-center"><?php echo $this->order('Last Visit', 'last_visit_date'); ?></th>
								<th class="text-center"><?php echo $this->order('Registration Date', 'register_date'); ?></th>
								<th class="text-center"><?php echo $this->order('ID', 'id'); ?></th>
							</tr>
						</thead>
						<tbody>
						<?php if($this->users != null)foreach ($this->users as $user){ ?>
							<tr>
								<td><input type="checkbox" id="record-<?php echo $user->id; ?>" name="record[]" value="<?php echo $user->id; ?>"></td>
								<td>
									<a href="<?php echo $this->url(array('module' => 'users', 'controller'=>'users', 'action'=>'edit', 'id' => $user->id));?>"><?php echo $user->real_name; ?></a>
								</td>
								<td class="text-center">
									<?php echo $user->username; ?>
								</td>
								<td class="text-center">
									<?php if ($user->block == true){ ?>
										<button type="button" onclick="$('#record-<?php echo $user->id; ?>')[0].checked = true; $('#task').val('disable');$(this).closest('form').submit();" class="btn btn-default btn-xs active" data-toggle="tooltip" title="Click to Enable User">
											<span class="glyphicon glyphicon-ok text-success"></span>
										</button>
									<?php }else{ ?>
										<button type="button" onclick="$('#record-<?php echo $user->id; ?>')[0].checked = true; $('#task').val('enable');$(this).closest('form').submit();" class="btn btn-default btn-xs" data-toggle="tooltip" title="Click to Disable User">
											<span class="glyphicon glyphicon-remove text-danger"></span>
										</button>
									<?php } ?>
								</td>
								<td class="text-center">
									<?php if ($user->active == 1){ ?>
										<button type="button" class="btn btn-default btn-xs active" data-toggle="tooltip" title="Activated">
											<span class="glyphicon glyphicon-ok text-primary"></span>
										</button>
									<?php }else{ ?>
										<button type="button" onclick="$('#record-<?php echo $user->id; ?>')[0].checked = true; $('#task').val('activate');$(this).closest('form').submit();" class="btn btn-default btn-xs" data-toggle="tooltip" title="Click to set Activated">
											<span class="glyphicon glyphicon-remove text-danger"></span>
										</button>
									<?php } ?>
								</td>
								<td class="text-center">
									<?php
									$rowsGroups = $user->findManyToManyRowset('Users_Model_DbTable_Group', 'Users_Model_DbTable_UserGroup');
									if($rowsGroups->count() == 1){
										$group = $rowsGroups->current();
										echo '<a href="' . $this->url(array('module' => 'users', 'controller'=>'groups', 'action'=>'edit', 'id' => $group->id)) . '" class="btn btn-default btn-xs btn-sm"><span class="glyphicon glyphicon-plug-user"></span> ' . $group->title . '</a><br/>';
									}elseif($rowsGroups->count() > 1){
										echo '<div class="btn-group">';
										echo '<button type="button" class="btn btn-default btn-xs btn-sm dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-plug-users"></span> ' . $rowsGroups->count() . ' groups <span class="caret"></span></button>';
										echo '<ul class="dropdown-menu text-left" role="menu">';
										foreach ($rowsGroups as $group){
											echo '<li><a href="' . $this->url(array('module' => 'users', 'controller'=>'groups', 'action'=>'edit', 'id' => $group->id)) . '">' . $group->title . '</a></li>';
										}
										echo '</ul>';
										echo '</div>';
									}
									?>
								</td>
								<td class="text-center"><?php echo $user->email; ?></td>
								<td class="text-center"><?php echo $user->last_visit_date; ?></td>
								<td class="text-center"><?php echo $user->register_date; ?></td>
								<td class="text-center"><span class="badge"><?php echo $user->id; ?></span></td>
							</tr>
						<?php } ?>
						</tbody>
					</table>
				</div>
				<?php echo $this->paginator;?>
			</div>
		</div>
	</div>
	<input value="<?php echo $this->filter['order_by']; ?>" name="order_by" id="order_by" type="hidden"/>
	<input value="<?php echo $this->filter['ordering']; ?>" name="ordering" id="ordering" type="hidden"/>
</form>