<form action="" id="adminForm" name="adminForm" method="post">	
	<div class="row">
		<nav class="navbar navbar-default" role="navigation">
			<div class="container-fluid">
			<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						<span class="sr-only">Toggle navigation</span>
						&nbsp;<span class="glyphicon glyphicon-cog"></span>&nbsp;
					</button>
					<a class="navbar-brand" href="#">Group Manager : Edit Group</a>
				</div>
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav navbar-right">
						<input id="task" name="task" type="hidden" value="edit"/>
						<button type="submit" class="btn btn-default btn-sm btn-primary navbar-btn"><span class="glyphicon glyphicon-floppy-saved"></span> Save</button>
						<button type="submit" onclick="$('#task').val('edit.close');" class="btn btn-default btn-sm navbar-btn"><span class="glyphicon glyphicon-floppy-remove"></span> Save & Close</button>
						<button type="submit" onclick="$('#task').val('edit.new');" class="btn btn-default btn-sm navbar-btn"><span class="glyphicon glyphicon-floppy-disk"></span> Save & New</button>
						<button type="submit" onclick="$('#task').val('edit.copy');" class="btn btn-default btn-sm navbar-btn"><span class="glyphicon glyphicon-floppy-disk"></span> Save & Copy</button>
						<button type="submit" onclick="$('#task').val('close');" class="btn btn-default btn-sm btn-danger navbar-btn"><span class="glyphicon glyphicon-remove"></span> Close</button>
					</ul>
				</div>
			</div>
		</nav>
		<div class="panel panel-default">
			<div class="panel-body">
				<div class="panel panel-default">
					<div class="panel-heading">Group Details</div>
					<div class="panel-body form-horizontal">
						<?php echo $this->form;?>
					</div>
				</div>
			</div>
		</div>
	</div>
</form>

