<form action="" id="adminForm" name="adminForm" method="post">	
	<div class="row">
		<nav class="navbar navbar-default" role="navigation">
			<div class="container-fluid">
			<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-2">
						<span class="sr-only">Toggle navigation</span>
						&nbsp;<span class="glyphicon glyphicon-cog"></span>&nbsp;
					</button>
					<a class="navbar-brand" href="#">Group Manager : Groups</a>
				</div>
				<div class="collapse navbar-collapse" id="navbar-collapse-2">
					<ul class="nav navbar-nav navbar-right">
						<input id="task" name="task" type="hidden" value="edit"/>
						<button type="button" onclick="$('#task').val('create');$(this).closest('form').submit();" class="btn btn-default btn-sm btn-primary navbar-btn" <?php echo ($this->isAllow('users', 'create') == true ? '' : ' disabled')?>><span class="glyphicon glyphicon-plus-sign"></span> New</button>
						<button type="button" onclick="if(!$(this).closest('form').find('table :checked').first().val()){alert('Please first make a selection from the list!');return false;}else{$('#task').val('edit');$(this).closest('form').submit();};" class="btn btn-default btn-sm navbar-btn"><span class="glyphicon glyphicon-edit"></span> Edit</button>
						<button type="button" onclick="if(!$(this).closest('form').find('table :checked').first().val()){alert('Please first make a selection from the list!');return false;}else{$('#task').val('delete');$(this).closest('form').submit();};" class="btn btn-default btn-sm btn-danger navbar-btn"><span class="glyphicon glyphicon-remove-sign"></span> Delete</button>
					</ul>
				</div>
			</div>
		</nav>
		<ul class="nav nav-tabs">
			<li><a href="<?= $this->url(array('module' => 'users', 'controller'=>'users', 'action'=>'index'), null, true); ?>">User</a></li>
			<li class="active"><a href="#">Group</a></li>
		</ul>
		<!-- Table -->
		<div class="panel panel-default tabs-panel">
			<div class="panel-body">
				<div class="row">
					<div class="col-sm-4 form-group">
						<div class="input-group">
							<input value="<?php echo $this->filter['search']; ?>" name="filter_search" id="filter_search" placeholder="Search Groups" type="text" class="form-control input-sm">
							<span class="input-group-btn">
								<button class="btn btn-default btn-sm" type="button" onclick="$(this).closest('form').submit();">Search</button>
								<button class="btn btn-default btn-sm" type="button" onclick="$('#filter_search').val(''); $(this).closest('form').submit();">Reset</button>
							</span>
						</div>
					</div>
					<div class="col-sm-8">
						<div class="form-inline form-full-right">
							<div class="form-group input-sm hidden-xs">
								<label>Filter by: </label>
							</div>
						    <div class="form-group">
						    	<?php echo $this->formSelect('filter_state', $this->filter['state'], array('class' => 'form-control input-sm', 'onchange' => '$(this).closest(\'form\').submit();'), array(
						    			'*' => ' - State - ',
						    			'0' => 'Can Edit',
						    			'1' => 'Protected'
						    	));?>
						    </div>
						</div>
					</div>
					<div class="clearfix"></div>
				</div>
				<div class="panel panel-default margin-fix table-responsive">
					<table class="table table-hover table-striped">
						<thead>
							<tr>
								<th width="1%"><input type="checkbox" onchange="$(this).closest('form').find('table :checkbox').prop('checked', this.checked);"></th>
								<th><?php echo $this->order('Real Name', 'title'); ?></th>
								<th class="text-center"><?php echo $this->order('Order', 'lft'); ?></th>
								<th class="text-center"><?php echo $this->order('Number Of Users', 'users'); ?></th>
								<th class="text-center"><?php echo $this->order('Protected', 'protected'); ?></th>
								<th class="text-center"><?php echo $this->order('ID', 'id'); ?></th>
							</tr>
						</thead>
						<tbody>
						<?php if($this->groups != null)foreach ($this->groups as $group){ ?>
							<tr>
								<td><input type="checkbox" id="record-<?php echo $group->id; ?>" name="record[]" value="<?php echo $group->id; ?>"></td>
								<td>
									<?php echo str_repeat('|—', $group->level); ?><a href="<?php echo $this->url(array('module' => 'users', 'controller'=>'groups', 'action'=>'edit', 'id' => $group->id));?>"><?php echo $group->title; ?></a>
								</td>	
								<td class="text-center">
									<span class="badge"><?php echo $group->getTable()->getNodeOrdering($group->id, $group->parent_id); ?></span>
								</td>						
								<td class="text-center"><span class="badge"><?php echo $group->users; ?></span></td>
								<td class="text-center">
									<?php if($group->protected == true){?>
										<button type="button" class="btn btn-default btn-xs active" data-toggle="tooltip" title="Is Protected"><span class="text-danger glyphicon glyphicon-lock"></span></button>
									<?php }else{ ?>
										<button type="button" class="btn btn-default btn-xs" data-toggle="tooltip" title="Can Edit"><span class="text-primary glyphicon glyphicon-plug-unlocked"></span></button>
									<?php } ?>
								</td>
								<td class="text-center"><span class="badge"><?php echo $group->id; ?></span></td>
							</tr>
						<?php } ?>
						</tbody>
					</table>
				</div>
				<?php echo $this->paginator;?>
			</div>
		</div>
	</div>
	<input value="<?php echo $this->filter['order_by']; ?>" name="order_by" id="order_by" type="hidden"/>
	<input value="<?php echo $this->filter['ordering']; ?>" name="ordering" id="ordering" type="hidden"/>
</form>