<form action="" id="adminForm" name="adminForm" method="post">
	<div class="row">
		<nav class="navbar navbar-default" role="navigation">
			<div class="container-fluid">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse"
						data-target="#navbar-collapse-2">
						<span class="sr-only">Toggle navigation</span> &nbsp;<span
							class="glyphicon glyphicon-cog"></span>&nbsp;
					</button>
					<a class="navbar-brand" href="#">Module Permission</a>
				</div>
				<div class="collapse navbar-collapse" id="navbar-collapse-2">
					<ul class="nav navbar-nav navbar-right">
						<button type="submit"
							class="btn btn-default btn-sm btn-primary navbar-btn">
							<span class="glyphicon glyphicon-floppy-saved"></span> Save
						</button>

					</ul>
				</div>
			</div>
		</nav>
		<div class="panel panel-default">
			<div class="panel-body">
				<div class="row">
					<div class="col-md-3">
						<h3>Modules</h3>
						<div class="list-group">
							<?php 
							$acl = Zendvn_Factory::getAcl();
							if($this->modules->count() > 0) foreach ($this->modules as $index => $module){ ?>
								<a href="#<?php echo $module->resource;?>" data-toggle="module" class="list-group-item<?php echo ($index == 0 ? ' active' : '')?>" onclick="$('a[data-toggle=module], div[data-toggle=module-content]').removeClass('active');$($(this).addClass('active').attr('href')).addClass('active');">
									<?php if($acl->hasRule($module->resource)){?>
										<span class="glyphicon glyphicon-warning-sign text-warning pull-right" data-toggle="tooltip" title="" data-original-title="Has set permission setting"></span>
									<?php }?>
									<?php echo $module->title; ?>
								</a>
							<?php }?>
						</div>
					</div>
					<div class="col-md-9">
						<h3>Permission</h3>
						<div class="tab-content">
							<?php if($this->modules->count() > 0) foreach ($this->modules as $index => $module){ ?>
								<div class="tab-pane <?php echo ($index == 0 ? ' active' : '')?>" id="<?php echo $module->resource;?>" data-toggle="module-content">
									<?php echo $acl->getForm($module->resource, $module->resource, $module->resource);?>
								</div>
							<?php }?>
						</div>
					</div>
				</div>
			</div>
		</div>

	</div>
</form>