	<div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Please Sign In</h3>
                    </div>
                    <div class="panel-body">
                        <?php echo $this->loginForm;?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <style>
		 .login-panel {
		    margin-top: 50%;
		}
	</style>