<div class="panel-body">
	<div class="row">
		<div class="col col-xs-2">
			<position>top-a</position>
		</div>
		<div class="col col-xs-2">
			<position>top-b</position>
		</div>
		<div class="col col-xs-2">
			<position>top-c</position>
		</div>
		<div class="col col-xs-2">
			<position>top-d</position>
		</div>
		<div class="col col-xs-2">
			<position>top-e</position>
		</div>
		<div class="col col-xs-2">
			<position>top-f</position>
		</div>
	</div>
	<div class="row">
		<div class="col col-xs-2">
			<position>header-a</position>
		</div>
		<div class="col col-xs-2">
			<position>header-b</position>
		</div>
		<div class="col col-xs-2">
			<position>header-c</position>
		</div>
		<div class="col col-xs-2">
			<position>header-d</position>
		</div>
		<div class="col col-xs-2">
			<position>header-e</position>
		</div>
		<div class="col col-xs-2">
			<position>header-f</position>
		</div>
	</div>
	<div class="row">
		<div class="col col-xs-12">
			<position>menu</position>
		</div>
	</div>
	<div class="row">
		<div class="col col-xs-4">
			<div class="row">
				<div class="col col-xs-4">
					<position>left-1</position>
				</div>
				<div class="col col-xs-4">
					<position>left-2</position>
				</div>
				<div class="col col-xs-4">
					<position>left-3</position>
				</div>
			</div>
		</div>
		<div class="col col-xs-8">
			<div class="row">
				<div class="col col-xs-4">
					<position>main-top-1</position>
				</div>
				<div class="col col-xs-4">
					<position>main-top-2</position>
				</div>
				<div class="col col-xs-4">
					<position>main-top-3</position>
				</div>
			</div>
			<div class="row">
				<div class="col col-xs-12">
					<main/>
				</div>
			</div>
			<div class="row">
				<div class="col col-xs-4">
					<position>main-bot-1</position>
				</div>
				<div class="col col-xs-4">
					<position>main-bot-2</position>
				</div>
				<div class="col col-xs-4">
					<position>main-bot-3</position>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col col-xs-6">
			<position>bottom-1</position>
		</div>
		<div class="col col-xs-6">
			<position>bottom-2</position>
		</div>
	</div>
	<div class="row">
		<div class="col col-xs-2">
			<position>footer-a</position>
		</div>
		<div class="col col-xs-2">
			<position>footer-b</position>
		</div>
		<div class="col col-xs-2">
			<position>footer-c</position>
		</div>
		<div class="col col-xs-2">
			<position>footer-d</position>
		</div>
		<div class="col col-xs-2">
			<position>footer-e</position>
		</div>
		<div class="col col-xs-2">
			<position>footer-f</position>
		</div>
	</div>
</div>