<form action="" id="adminForm" name="adminForm" method="post">	
	<div class="row">
		<nav class="navbar navbar-default" role="navigation">
			<div class="container-fluid">
			<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-2">
						<span class="sr-only">Toggle navigation</span>
						&nbsp;<span class="glyphicon glyphicon-cog"></span>&nbsp;
					</button>
					<a class="navbar-brand" href="#">Article Manager : Articles</a>
				</div>
				<div class="collapse navbar-collapse" id="navbar-collapse-2">
					<ul class="nav navbar-nav navbar-right">
						<input id="task" name="task" type="hidden" value="edit"/>
							<button type="button" onclick="$('#task').val('create');$(this).closest('form').submit();" class="btn btn-default btn-sm btn-primary navbar-btn" <?php echo ($this->isAllow('contents', 'create') == true ? '' : ' disabled')?>><span class="glyphicon glyphicon-plus-sign"></span> New</button>
							<button type="button" onclick="if(!$(this).closest('form').find('table :checked').first().val()){alert('Please first make a selection from the list!');return false;}else{$('#task').val('edit');$(this).closest('form').submit();};" class="btn btn-default btn-sm navbar-btn" <?php echo ($this->isAllow('contents', 'edit') == true ? '' : ' disabled')?>><span class="glyphicon glyphicon-edit"></span> Edit</button>
							<button type="button" onclick="if(!$(this).closest('form').find('table :checked').first().val()){alert('Please first make a selection from the list!');return false;}else{$('#task').val('publish');$(this).closest('form').submit();};" class="btn btn-default btn-sm navbar-btn" <?php echo ($this->isAllow('contents', 'editState') == true ? '' : ' disabled')?>><span class="glyphicon glyphicon-ok text-success"></span> Publish</button>
							<button type="button" onclick="if(!$(this).closest('form').find('table :checked').first().val()){alert('Please first make a selection from the list!');return false;}else{$('#task').val('unpublish');$(this).closest('form').submit();};" class="btn btn-default btn-sm navbar-btn" <?php echo ($this->isAllow('contents', 'editState') == true ? '' : ' disabled')?>><span class="glyphicon glyphicon-remove text-danger"></span> Unpublish</button>			
							<button type="button" onclick="if(!$(this).closest('form').find('table :checked').first().val()){alert('Please first make a selection from the list!');return false;}else{$('#task').val('featured');$(this).closest('form').submit();};" class="btn btn-default btn-sm navbar-btn" <?php echo ($this->isAllow('contents', 'editState') == true ? '' : ' disabled')?>><span class="glyphicon glyphicon-star text-primary"></span> Featured</button>
							<button type="button" onclick="if(!$(this).closest('form').find('table :checked').first().val()){alert('Please first make a selection from the list!');return false;}else{$('#task').val('unfeatured');$(this).closest('form').submit();};" class="btn btn-default btn-sm navbar-btn" <?php echo ($this->isAllow('contents', 'editState') == true ? '' : ' disabled')?>><span class="glyphicon glyphicon-star-empty"></span> Unfeatured</button>			
							<button type="button" onclick="if(!$(this).closest('form').find('table :checked').first().val()){alert('Please first make a selection from the list!');return false;}else{$('#task').val('delete');$(this).closest('form').submit();};" class="btn btn-default btn-sm btn-danger navbar-btn" <?php echo ($this->isAllow('contents', 'delete') == true ? '' : ' disabled')?>><span class="glyphicon glyphicon-remove-sign"></span> Delete</button>
						
					</ul>
				</div>
			</div>
		</nav>
		<ul class="nav nav-tabs">
			<li><a href="<?= $this->url(array('module' => 'contents', 'controller'=>'categories', 'action'=>'index'), null, true); ?>">Category Manager</a></li>
			<li class="active"><a href="#">Article Manager</a></li>
		</ul>
		<div class="panel panel-default tabs-panel">
			<div class="panel-body">
				<div class="row">
					<div class="col-sm-4 form-group">
						<div class="input-group">
							<input value="<?php echo $this->filter['search']; ?>" name="filter_search" id="filter_search" placeholder="Search Article" type="text" class="form-control input-sm">
							<span class="input-group-btn">
								<button class="btn btn-default btn-sm" type="button" onclick="$(this).closest('form').submit();">Search</button>
								<button class="btn btn-default btn-sm" type="button" onclick="$('#filter_search').val(''); $(this).closest('form').submit();">Reset</button>
							</span>
						</div>
						
					</div>
					<div class="col-sm-8">
						<div class="form-inline form-full-right">
							<div class="form-group input-sm hidden-xs">
								<label>Filter by: </label>
							</div>
							<div class="form-group">
								<?php echo $this->formSelect('filter_category', $this->filter['category'], array('class' => 'form-control input-sm', 'onchange' => '$(this).closest(\'form\').submit();'), array(
						    			'*' => ' - Category - '
						    	) + $this->select_categories);?>
					    	</div>
						    <div class="form-group">
						    	<?php echo $this->formSelect('filter_status', $this->filter['status'], array('class' => 'form-control input-sm', 'onchange' => '$(this).closest(\'form\').submit();'), array(
						    			'*' => ' - Status - ',
						    			'publish' => 'Publish',
						    			'unpublish' => 'Unpublish'
						    	));?>
						    </div>
						    <div class="form-group">
						    	<?php echo $this->formSelect('filter_featured', $this->filter['featured'], array('class' => 'form-control input-sm', 'onchange' => '$(this).closest(\'form\').submit();'), array(
						    			'*' => ' - Featured - ',
						    			'1' => 'Featured',
						    			'0' => 'Unfeatured'
						    	));?>
						    </div>
					    </div>
					</div>
					<div class="clearfix"></div>	
				</div>
				<div class="panel panel-default margin-fix table-responsive">
					<table class="table table-hover table-striped">
						<thead>
							<tr>
								<th class="text-center" width="1%"><input type="checkbox" onchange="$(this).closest('form').find('table :checkbox').prop('checked', this.checked);"></th>
								<th class="text-center" width="1%">Image</th>
								<th><?php echo $this->order('Title', 'title'); ?></th>
								<th width="15%"><?php echo $this->order('Category', 'category'); ?></th>
								<th class="text-center" width="5%"><?php echo $this->order('Status', 'status'); ?></th>
								<th class="text-center" width="10%"><?php echo $this->order('Featured', 'featured'); ?></th>
								<th class="text-center" width="10%">Access</th>
								<th class="text-center" width="10%"><?php echo $this->order('Date', 'created_date'); ?></th>
								<th class="text-center" width="5%"><?php echo $this->order('Hits', 'hits'); ?></th>
								<th class="text-center" width="5%"><?php echo $this->order('ID', 'id'); ?></th>
							</tr>
						</thead>
						<tbody>
							<?php if($this->articles) foreach ($this->articles as $article){ ?>
									<tr>
										<td><input type="checkbox" id="record-<?php echo $article->id; ?>" name="record[]" value="<?php echo $article->id; ?>"></td>
										<td>
											<?php if(
													$this->isAllow('contents.articles.' . $article->id, 'edit') ||
													($this->isAllow('contents.categories.' . $article->category_id, 'editOwn') && $article->created_user_id == $user->id)
											){?>
												<a href="<?php echo $this->url(array("module"=>"contents", "controller"=>"articles", "action"=>"edit", "id"=>$article->id));?>" class="thumbnail" style="width: 46px; height: 46px; margin: 0;padding:2px;">
												<?php if($article->image){ ?>
													<img src="<?php echo $this->baseUrl('/modules/contents/images/thumbnails/' . $article->image);?>">
												<?php }else{ ?>
													<img data-src="holder.js/100%x100%" alt="none">
												<?php }?>
												</a>
											<?php }else{ ?>
												<a href="#" onclick="return false;" class="thumbnail" style="width: 46px; height: 46px; margin: 0;padding:2px;">
												<?php if($article->image){ ?>
													<img src="<?php echo $this->baseUrl('/modules/contents/images/thumbnails/' . $article->image);?>">
												<?php }else{ ?>
													<img data-src="holder.js/100%x100%" alt="none">
												<?php }?>
												</a>
											<?php }?>
										</td>
										<td>
										<?php if($article->hasRule()){ ?>
											<span class="glyphicon glyphicon-warning-sign text-warning pull-right" data-toggle="tooltip" title="Has set permission setting"></span>
										<?php } ?>
										<?php if(
												$this->isAllow('contents.articles.' . $article->id, 'edit') ||
												($this->isAllow('contents.categories.' . $article->category_id, 'editOwn') && $article->created_user_id == $user->id)
										){?>
											<a href="<?php echo $this->url(array("module"=>"contents", "controller"=>"articles", "action"=>"edit", "id"=>$article->id));?>"><?php echo $article->title;?></a> <small>(Alias: <?php echo $article->alias;?>)</small>
										<?php }else{ ?>
											<span class="text-muted"><?php echo $article->title;?> <small>(Alias: <?php echo $article->alias;?>)</small></span>
										<?php }?>
										</td>
										<td><?php echo $article->category; ?></td>
										<td class="text-center">
											<?php if ($article->status == 'publish'){ ?>
												<button type="button" onclick="$('#record-<?php echo $article->id; ?>')[0].checked = true; $('#task').val('unpublish');$(this).closest('form').submit();"  class="btn btn-default btn-xs active" data-toggle="tooltip" title="Click to set Unpublished"<?php echo ($this->isAllow('contents', 'editState') == true ? '' : ' disabled')?>>
													<span class="glyphicon glyphicon-ok text-success"></span>
												</button>
											<?php }else{ ?>
												<button type="button" onclick="$('#record-<?php echo $article->id; ?>')[0].checked = true; $('#task').val('publish');$(this).closest('form').submit();" class="btn btn-default btn-xs" data-toggle="tooltip" title="Click to set Published"<?php echo ($this->isAllow('contents', 'editState') == true ? '' : ' disabled')?>>
													<span class="glyphicon glyphicon-remove text-danger"></span>
												</button>
											<?php } ?>
										</td>
										<td class="text-center">
											<?php if ($article->featured == true){ ?>
												<button type="button" onclick="$('#record-<?php echo $article->id; ?>')[0].checked = true; $('#task').val('unfeatured');$(this).closest('form').submit();"  class="btn btn-default btn-xs active" data-toggle="tooltip" title="Click to set Unfeatured"<?php echo ($this->isAllow('contents', 'editState') == true ? '' : ' disabled')?>>
													<span class="glyphicon glyphicon-star text-primary"></span>
												</button>
											<?php }else{ ?>
												<button type="button" onclick="$('#record-<?php echo $article->id; ?>')[0].checked = true; $('#task').val('featured');$(this).closest('form').submit();" class="btn btn-default btn-xs" data-toggle="tooltip" title="Click to set Featured"<?php echo ($this->isAllow('contents', 'editState') == true ? '' : ' disabled')?>> 
													<span class="glyphicon glyphicon-star-empty"></span>
												</button>
											<?php } ?>
										</td>
										<td class="text-center">
											<?php
												if(($access = $article->getGroupAccess()) != null){
													if($access == '*'){
														echo '<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-plug-users"></span> All Groups</button>';
													}else{
														echo '<div class="btn-group">';
														echo '<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-plug-users"></span> ' . count($access) . ' groups <span class="caret"></span></button>';
														echo '<ul class="dropdown-menu text-left" role="menu">';
														foreach ($access as $id => $group){
															echo '<li><a href="' . $this->url(array('module' => 'users', 'controller'=>'groups', 'action'=>'edit', 'id' => $id)) . '">' . $group . '</a></li>';
														}
														echo '</ul>';
														echo '</div>';
													}
												}
											?>
										</td>
										<td class="text-center">
											<?php echo $article->created_date; ?>
										</td>
										<td class="text-center">
											<?php echo $article->hits; ?>
										</td>
										<td class="text-center"><span class="badge"><?php echo $article->id; ?></span></td>
									</tr>
							<?php } ?>
						</tbody>
					</table>
				</div>
				<?php echo $this->paginator;?>
			</div>
		</div>
	</div>
	<input value="<?php echo $this->filter['order_by']; ?>" name="order_by" id="order_by" type="hidden"/>
	<input value="<?php echo $this->filter['ordering']; ?>" name="ordering" id="ordering" type="hidden"/>
</form>

